### PR TITLE
Linux+

### PR DESCRIPTION
**Pull request by rwhitworth**
C697 seems straight forward.
C698 is odd in that the uCertify link isn't unique to this class.  So instead I included the 'provision' URL.

Please let me know if both of these are done properly, as I have no way to test locally (that I'm aware of).  If these are correct then I'll file more PRs for additional classes.

Thanks for this wonderful addon!

### CODE REVIEW

**Comment by bamhm182** [comment]
It shouldn't matter that the uCertify link isn't unique to that class. You should be able to link to a uCertify course from as many classes as you would like, but either URLs should be fine. I've committed both you pulls and will be submitting a new version to the webstore in just a moment.

**Comment by bamhm182** [comment]
I decided to try and look at the classes you added, and it turns out that they were ones I already had credit for, so I was able to view them. It looks like they may have a different format than what I programmed the extension for. Can I get you to confirm whether or not there is an arrow that lets you hide the section containing the Course Mentor dropdowns for you. In the README, there is a screenshot that shows an arrow to the top left of the Quick Links that lets you hide the section. If that isn't there, I may have extra work to do.

**Comment by rwhitworth** [comment]
The provision link in C698 works fine and the arrow for hiding the mentor dropdown is present.
The uCertify link in C697 is missing as is the quick links box and the arrow for hiding the mentor dropdown is missing.

I think C697 is missing the arrow for hiding the mentor even without the plugin enabled.  I think this is a misconfiguration on WGU's end.  The 'overview' pane for C697 is even different.

**Comment by bamhm182** [comment]
Well, I did some digging and found out something interesting. The link I have in my course for Operating Systems II - C698 is 10840005, yours is 4780002. They look like they're the exact same course, but with different class ids. Thought that was interesting.

As for the reason why you're not seeing it under C697, I have it set to add the Quick Links under a class defined as:
responsive--hidden--sm responsive--hidden--xs ng-scope

For some reason, C697's class for that column is:
col col--lg--4 margin--bottom--30 responsive--hidden--sm responsive--hidden--xs ng-scope

These aren't counted as the same, so I will have to add something to check for that class as well. The update should be pushed soon.

**Comment by bamhm182** [comment]
Turns out that what I thought the issue was wasn't actually what the issue was. I think it had something to do with my timers. Either way, I believe I fixed it and the Chrome Web Store should receive the new version in the near future. Let me know if it works for you.

**Pull request merged**
