### PR TITLE
Added YouTube support, added more C100 & C225 resources, and misc. README changes

### PR DESCRIPTION
**Pull request by ZacharyDavidSaunders**

### CODE REVIEW

**Comment by ZacharyDavidSaunders** [comment]
I forgot to add it in the title, but I also made it so every Quick Link opens in a new tab. Previously, some of the WGU links did this by default, but some did not and they would redirect you out of your portal.

**Comment by bamhm182** [comment]
My automated build system for updating the version on the chrome web store broke and i won't be able to fix it until like Thursday or Friday. This commit may take a little time unless I can figure out how to update it from my phone.

**Comment by ZacharyDavidSaunders** [comment]
Okay, no worries.

**Comment by bamhm182** [comment]
Got a little busier than I thought I would. I just got around to fixing my auto-updater and testing it out. Chrome webstore should be updated automatically again.

**Comment by ZacharyDavidSaunders** [comment]
Great. Thanks for following up.

**Pull request merged**
